### ISSUE TITLE
You can do wall jumps in trigger colliders

### ISSUE THREAD

**Issue by taki640** [KybernetikGames/platformer#9]
# Environment

- Platformer Game Kit Version Number: 1.0
- Unity Version: 2020.3.33f1
- Platform: Windows

# Description

Trigger collisions are identified as walls so you can wall jump in them.

# Reproduction

Steps to reproduce the bug:

1. Create a box collision and set Is Trigger on.
2. Jump while inside the box.

https://user-images.githubusercontent.com/99517475/162847960-84ad442b-4177-469e-9a18-10d38ce39e0c.mp4

**Comment by taki640** [comment]
So, I experimented a bit and found a way to fix this but I'm new to Unity and C# so I don't know if it's the best way.
In the `bool CheckForWallJump` I changed the `var layers` to get only the layer "Wall".  Personally I think this is better because I can choose where the wall jump is allowed.

```
private bool CheckForWallJump(Vector2 direction)
        {
            var bounds = Character.Body.Collider.bounds;
            var layers = LayerMask.GetMask("Wall");
            var count = Physics2D.BoxCastNonAlloc(
                bounds.center, bounds.size, Character.Body.Rotation, direction,
                PlatformerUtilities.OneRaycastHit, _DetectionDistance, layers);

            if (count > 0)
            {
                _WallNormal = -direction;
                return true;
            }
            else return false;
        }
```

**Comment by KybernetikGames** [comment]
You can actually prevent the cast from hitting triggers specifically:

```
            var queriesHitTriggers = Physics2D.queriesHitTriggers;
            Physics2D.queriesHitTriggers = false;

            var count = Physics2D.BoxCastNonAlloc(
                bounds.center, bounds.size, Character.Body.Rotation, direction,
                PlatformerUtilities.OneRaycastHit, _DetectionDistance, layers);

            Physics2D.queriesHitTriggers = queriesHitTriggers;
```

I'll put that in the next version.

If you do want to also enable/disable wall jumping for specific layers separately from the regular collision layers, I'd give `WallJumpState` a `LayerMask` field so you can set it in the Inspector rather than hard coding the layer name in the script. Or if you prefer hard coding it, I'd at least put it in a static field so it only has to evaluate the mask once instead of repeating it every time:

```
public static class Layers
{
    public static readonly int WallJumpMask = LayerMask.GetMask("Wall");
}
```

It has to be a separate class because `LayerMask.GetMask` isn't allowed to be called in a field initializer in a `MonoBehaviour`.

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available and has this issue fixed.
